### ISSUE TITLE
ROI Z slice

### ISSUE THREAD

**Issue by Tom-TBT** [jalexop/Metrolo2Omero#1]
Hello Ioannis,
let's try out github features for you. An issue I spotted is that you do not keep record of which Z slice the ROI was originally detected at.

Two options to solve this:
* You keep the center coordinates of the beads in your table
* You assign the Z position of your ROI to the central Z slice

I would favor the second, as selecting an ROI in the iviewer would jump to the slice where the bead was detected. (drawback, the ROI is not showing on all Z slices)

I think `Roi.setPosition(<slice>)` would do the job in the Fiji macro.

**Comment by jalexop** [comment]
Hi Tom, thanks for pointing this out.
I was setting the correct z position before drawing the ROI, but apparently it was not kept.
I fixed it now and it will be uploaded by tomorrow as the newest version. 
Best
Ioannis
